### ISSUE TITLE
product hunt logo not centered

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/auroraeditor.com#295]
### Description

product hunt logo not centered

![IMG_8649](https://github.com/AuroraEditor/auroraeditor.com/assets/1290461/fe71ebb5-486c-4879-8fe4-363c28f499a0)

### To Reproduce

Scroll down

### Expected behavior

Be centered

### Version information

N/A

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by nanashili** [comment]
Need to add padding of 15 horizontally to the descriptions too
