### ISSUE TITLE
Download button should hide on non Mac user agent

### ISSUE THREAD

**Issue by nanashili** [AuroraEditor/auroraeditor.com#299]
### Description

The download button visible on user agents that are not a Mac!

### To Reproduce

Go to the website on mobile and notice it still being visible

### Expected behavior

Should be hidden on non Mac platforms

### Version information

N/A

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
The download button should be available on every platform, we can trigger a warning but it should not be hidden!

**Comment by nanashili** [comment]
I disagree, since AE is only ever available of Mac it makes no sense to have it visible

**Comment by 0xWDG** [comment]
It should be visible with a warning or so, I can even download whole OSes on my iPad if I want/feel the need to.

also people who change their user agent are not able to download if they are still on Mac but change it to e.g. edge on windows.

**Comment by nanashili** [comment]
Closing issue with the following commit: https://github.com/AuroraEditor/auroraeditor.com/commit/f8c862e0ded8edc468a63f3eba79498f9b93728f

It keeps the download button but adds a notice to the download specifically the nightly one!
