### ISSUE TITLE
Navbar styling

### ISSUE THREAD

**Issue by Keith-Web3** [AuroraEditor/auroraeditor.com#375]
The current active state of the links in the navbar would most likely be initially perceived as inactive links due to the current styling. A better way to denote that a particular route is active would be to use the gradient color used in the headers as the color for the active route link.

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by alexchrysovergis** [comment]
You raise a good point!

I tested this locally and found that the gradient didn't work all that well visually. 

What I opted for instead was to homogenize the hover and active states in both dark mode and light mode.

**Light Mode:**

![image](https://github.com/user-attachments/assets/aab6a6ef-01ef-42a1-99ef-e7295f9e2f00)

**Dark Mode:**

![image](https://github.com/user-attachments/assets/781bf5d7-1c5d-48a4-ac8c-8155db8fda3f)

**Comment by alexchrysovergis** [comment]
@aurora-care-bear please assign me

**Comment by aurora-care-bear** [comment]
@alexchrysovergis You are assigned now, to unassign comment `@aurora-care-bear please unassign me`.

**Comment by 0xWDG** [comment]
Fixed in #380
