### ISSUE TITLE
Unstyled Mastodon Link at the Bottom of the Website

### ISSUE THREAD

**Issue by alexchrysovergis** [AuroraEditor/auroraeditor.com#377]
There is an unstyled link to [AuroraEditor's Mastodon](https://mastodon.social/@AuroraEditor) at the bottom of the webpage.

![image](https://github.com/user-attachments/assets/a2a96802-bbbb-4ddc-bd3b-9bbbc4f68590)

If needed, I can either remove the link or move it inside the existing  ```<aside class="section socials-router-links">``` element alongside the other links.

**Comment by aurora-care-bear** [comment]
@alexchrysovergis You are assigned now, to unassign comment `@aurora-care-bear please unassign me`.

**Comment by alexchrysovergis** [comment]
This is what I ended up doing:

- Corrected the visibility property to hide the original unstyled link.
- Added the Mastodon link inside the ```<aside class="section socials-router-links">``` element alongside the other social media links.

The icon I used is from [UXWing](https://uxwing.com/mastodon-icon/), which has a license stating that "All icons on this site can be used in personal, commercial, and client projects without any attribution or credit."

![image](https://github.com/user-attachments/assets/734c6ad5-3b32-4f43-ae9f-7029ca4beb97)
